name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.1

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt
      
      - name: Run rust-clippy
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
      
      - name: Build
        run: cargo build --verbose
      
      - name: Run tests
        run: cargo test --verbose
      
      - name: Build Docs
        run: cargo doc 
             && cargo doc --no-deps 
             && rm -rf ./docs 
             && echo "<meta http-equiv=\"refresh\" content=\"0; url=weather\">" > target/doc/index.html 
             && cp -r target/doc ./docs
